---
ID: "093b7fda-ca5a-49bf-9b2b-283c893647ad"
Parent: "2ca83251-ab47-4bf5-9671-ecb9c00a5e11"
Template: "a99866e5-08e7-44d8-8a52-f8e26bcd3714"
Path: /sitecore/templates/Project/Habitat/Page Types/RssLoaderNews List/__Standard Values
DB: master
SharedFields:
- ID: "19b597d3-2edd-4ae2-aefe-4a94c7f10e31"
  Hint: __Source Item
  Value: "sitecore://master/{9ABC1BBC-1506-49E6-890C-82A79C36F246}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{9ABC1BBC-1506-49E6-890C-82A79C36F246}?lang=en&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190531T133900Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
